Problem Statement : Hospital Patient Data Analysis
Context:
A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.
Tasks:
1.	Load the patient dataset and show summary with info().
2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].
4.	Use groupby to find total bill amount per department.
5.	Remove duplicate patient records based on PatientID.
6.	Fill missing BillAmount values with the mean bill amount.
7.	Merge the billing dataset with patient dataset on PatientID.
8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).
9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).
Expected Outcome:
•	Final cleaned dataset with accurate billing info.
•	All missing values handled, merged dataset across PatientID.
•	Ability to perform further analytics on department-wise revenue or doctor performance.

In [2]:
import pandas as pd 

#1.loading the data
patient_data = pd.read_csv("Patient_Data.csv")
patient_data

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [3]:
billing_data = pd.read_csv("Billing_Data.csv")
billing_data

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [8]:
patient_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [9]:
billing_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         5 non-null      int64
 1   InsuranceCovered  5 non-null      int64
 2   FinalAmount       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [6]:
patient_data.describe()

        PatientID   BillAmount  ReceptionistID
count    6.000000     4.000000        6.000000
mean   102.666667  5925.000000        1.666667
std      1.632993  1192.686044        0.816497
min    101.000000  5000.000000        1.000000
25%    101.250000  5000.000000        1.000000
50%    102.500000  5600.000000        1.500000
75%    103.750000  6525.000000        2.000000
max    105.000000  7500.000000        3.000000

In [12]:
#2.column selection

columns = ['PatientID', 'Department', 'Doctor', 'BillAmount']
df = patient_data[columns]
df

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [15]:
#3.Dropping columns

df.drop(columns= ['ReceptionistID', 'CheckInTime'],errors='ignore')

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [16]:
#4.Grouping by to find total amount per department

df.groupby('Department')['BillAmount'].sum()

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

In [25]:
#5.Removing duplicate patients record

df.drop_duplicates(subset=['PatientID'])

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John      5925.0
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose      5925.0

In [36]:
#6.Filling the missing values of BillAmount


bill = df['BillAmount'].mean()
df.loc[:,'BillAmount'] = df['BillAmount'].fillna(bill)
df
#.loc[row_indexer,col_indexer]

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John      5925.0
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose      5925.0
5        101   Cardiology  Dr. Smith      5000.0

In [41]:
#7.Merging the dataset

billing_data = pd.read_csv("Billing_Data.csv")
merging_data = pd.merge(patient_data,billing_data,on='PatientID')
merging_data

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,2000,3000
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00,3000,3200
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45,1000,4000
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,2000,3000

In [44]:
#8.Concatenate of rows-wise

new_patients_df = pd.DataFrame({'PatientID':[101],'Name':['Alice']})
combination_row = pd.concat([merging_data, new_patients_df], axis=0)
combination_row

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,1.0,2023-01-10 09:00,2000.0,3000.0
1,102,Bob,Neurology,Dr. John,NaN,2.0,2023-01-11 10:30,1500.0,3500.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1.0,2023-01-12 11:00,2500.0,5000.0
3,104,David,Cardiology,Dr. Smith,6200.0,3.0,2023-01-13 12:00,3000.0,3200.0
4,105,Eva,Dermatology,Dr. Rose,NaN,2.0,2023-01-14 08:45,1000.0,4000.0
5,101,Alice,Cardiology,Dr. Smith,5000.0,1.0,2023-01-10 09:00,2000.0,3000.0
0,101,Alice,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
#9.Concatenate of coulmns

data_list = [[10,20],[30,40]]
new_columns_df = pd.DataFrame([data_list], columns=['col1','col2'])
combination_clm = pd.concat([combination_row, new_columns_df], axis=1)
combination_clm

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,InsuranceCovered,FinalAmount,col1,col2
0,101,Alice,Cardiology,Dr. Smith,5000.0,1.0,2023-01-10 09:00,2000.0,3000.0,"[10, 20]","[30, 40]"
1,102,Bob,Neurology,Dr. John,NaN,2.0,2023-01-11 10:30,1500.0,3500.0,NaN,NaN
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1.0,2023-01-12 11:00,2500.0,5000.0,NaN,NaN
3,104,David,Cardiology,Dr. Smith,6200.0,3.0,2023-01-13 12:00,3000.0,3200.0,NaN,NaN
4,105,Eva,Dermatology,Dr. Rose,NaN,2.0,2023-01-14 08:45,1000.0,4000.0,NaN,NaN
5,101,Alice,Cardiology,Dr. Smith,5000.0,1.0,2023-01-10 09:00,2000.0,3000.0,NaN,NaN
0,101,Alice,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[10, 20]","[30, 40]"